name: antifraud_flutter
description: "A new Flutter project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: uz.tbm.antifraud_flutter.antifraud_flutter
        pluginClass: AntifraudFlutterPlugin
      ios:
        pluginClass: AntifraudFlutterPlugin